# Generated by Django 4.2 on 2023-04-17 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Possition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('EmpCode', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=50)),
                ('Possition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeRegister.possition')),
            ],
        ),
    ]
